version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgre_data:/var/lib/postgresql/data
    networks:
      - appnetwork

volumes:
  postgre_data:

networks:
  appnetwork:
    driver: bridge